version: "3.1"

networks:
  net1:

services:
  postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "masterkey"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - "6379:6379"

